org.gradle.jvmargs=-Xms512m -Xmx2048m
org.gradle.configuration-cache=true
android.useAndroidX=true
android.enableJetifier=false

# customize for thirdparty build variant
thirdparty.slug=thirdparty
thirdparty.applicationId=com.example.thirdparty
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
